title: 点名器
email: sdxjzsq@126.com
title: "点名器"
description: 
  "上课点名器"
url: "https://xjzsq.github.io/naming/"
baseurl: "" # Don't change


weibo_username:     sdxjzsq
zhihu_username:     xjzsq
github_username:    xjzsq
twitter_username:   xjzsq

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# gems: [jekyll-paginate]

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
